---
title: "Lessons"
description: ""
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Effective Visual Communication

This lecture covers three core concepts of visual communication. First, I will discuss how to engage your audience by telling a story. Second, I will provide high-level guidance for designing visualizations that make a clear point. Third, I will describe key design principles that ensure your figures will be readable by people with vision impairments, and specifically impairments of color perception.

<p class="nospace">Materials:</p>

- [Slides](slides/effective-communication.html)  

## From Data to Visualisation 1

Visualizing amounts; visualizing distributions; visualizing associations and trends

<p class="nospace">Materials:</p>

- [Slides](slides/data-to-visualization-1.html)

## From Data to Visualisation 2

Visualizing uncertainty; visualizing geospatial data

<p class="nospace">Materials:</p>

- [Slides](slides/data-to-visualization-2.html)

## Principles of Figure Design 

Colors; compound figures; infographics

<p class="nospace">Materials:</p>

- [Slides](slides/figure-design.html)

## Reuse {.appendix}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Any computer code (R, HTML, CSS, etc.) in slides and worksheets, including in slide and worksheet sources, is also licensed under [MIT](https://github.com/wilkelab/SDS375/LICENSE.md). Note that figures in slides may be pulled in from external sources and may be licensed under different terms. For such images, image credits are available in the slide notes, accessible via pressing the letter 'p'.
