---
title: "Workshops"
description: ""
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Materials for past and present workshops. Many workshop materials are based on content from my semester-long [data visualization course at UT Austin.](https://wilkelab.org/SDS375/)

<strong class="nospace" id="2024-08-12">2024-08-12: Effective Data Visualization with ggplot2</strong>

All workshop materials will be posted [here.](materials/positconf2024.html)

<strong class="nospace" id="2024-06-24">2024-06-24: Visualizing Uncertainty and Trends</strong>

- Keynote, June 24 2024: [slides](materials/2024-06-24.html)
- Workshop, June 27 2024:
  - [Quarto notebook](materials/2024-06-27.qmd)
  - [HTML](materials/2024-06-27.html)
  - [HTML with solutions](materials/2024-06-27-solutions.html)

<strong class="nospace"  id="2024-06-20">2024-06-20: Effective Visual Communication with R</strong>

Workshop in [support of Ukraine.](https://sites.google.com/view/dariia-mykhailyshyna/main/r-workshops-for-ukraine#h.95gc1ocexdze) To work through all the examples provided, you will need the following R packages: tidyverse, cowplot, ggiraph, sf, patchwork

- [Slides Part 1](materials/2024-06-20-part1.html)
- [Slides Part 2](materials/2024-06-20-part2.html)
- [Slides Part 2, without interactivity](materials/2024-06-20-part2-minimal.html) (Some browsers crash when there are too many interactive examples in one slide set.)

<strong class="nospace"  id="2024-05-28">2024-05-28: Effective Visual Communication</strong>

- [Slides Part 1](materials/2024-05-28-part1.html) (telling a story, making a point, making figures accessible)
- [Slides Part 2](materials/2024-05-28-part2.html) (figure composition and context, text annotations, overplotting)

## Reuse {.appendix}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Any computer code (R, HTML, CSS, etc.) in slides and worksheets, including in slide and worksheet sources, is also licensed under [MIT](https://github.com/wilkelab/SDS375/LICENSE.md). Note that figures in slides may be pulled in from external sources and may be licensed under different terms.