---
title: "posit::conf(2024): Effective Data Visualization with ggplot2"
description: ""
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Materials for posit::conf(2024) workshop, [Monday, Aug. 12, 9am](https://reg.conf.posit.co/flow/posit/positconf24/publiccatalog/page/publiccatalog/session/1707334048207001SOYr)

### 1. Color scales and color spaces

- Slides: [[html]](positconf2024-slides-colors.html)
- Exercises: [[html]](positconf2024-colors.html) [[qmd]](positconf2024-colors.qmd)


### 2. Plot design with themes and axes

- Worksheet: [[html]](positconf2024-themes.html) [[qmd]](positconf2024-themes.qmd)


### 3. Sprucing up your legends

- Worksheet: [[html]](positconf2024-legends.html) [[qmd]](positconf2024-legends.qmd)
- Solutions: [[html]](positconf2024-legends-solutions.html) 

### 4. Gradient and pattern fills

- Worksheet: [[html]](positconf2024-pattern-fill.html) [[qmd]](positconf2024-pattern-fill.qmd)


## Reuse {.appendix}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Any computer code (R, HTML, CSS, etc.) in slides and worksheets, including in slide and worksheet sources, is also licensed under [MIT](https://github.com/wilkelab/SDS375/LICENSE.md). Note that figures in slides may be pulled in from external sources and may be licensed under different terms.