---
title: "Effective Data Visualization with ggplot2, Part 1"
format: html
editor: visual
---

## Required packages

Install the required packages:

```{r}
#| eval = FALSE

# Run this command to install the required packages.
# You need to do this only once.
install.packages(
  c(
    "tidyverse", "cowplot", "sf", "ragg"
  )
)
```

## 1. Plots overlaid on a map

We'll be visualizing state-level election results from the 2016 US presidential election.

```{r}
#| message = FALSE

library(tidyverse)
library(sf)          # for manipulating geospatial data
library(grid)        # for pattern creation

# data taken from: https://github.com/john-guerra/US_Elections_Results/tree/master
votes_2016 <- read_csv("https://wilkelab.org/dataviz_shortcourse/datasets/2016_US_County_Level_Presidential_Results.csv") |>
  mutate(
    fips = str_pad(combined_fips, 5, pad = "0"),
    state = state_abbr
  )
  
votes_long <- votes_2016 |>
  mutate(
    other = total_votes - votes_dem - votes_gop
  ) |>
  select(
    state, fips, democratic = votes_dem, republican = votes_gop, other
  ) |>
  pivot_longer(c(-state, -fips), names_to = "party", values_to = "votes")

```

### Exercises
