---
title: "posit::conf(2024): Effective Data Visualization with ggplot2"
description: ""
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Materials for posit::conf(2024) workshop, [Monday, Aug. 12, 9am](https://reg.conf.posit.co/flow/posit/positconf24/publiccatalog/page/publiccatalog/session/1707334048207001SOYr)

To run all code examples on your own install of R, make sure you have a recent version of R (at least 4.3), a recent version of ggplot2 (at least 3.5.0), and install the following packages:

```r
install.packages(
  c( 
    "tidyverse", "palmerpenguins", "shiny", "shinyjs", "RCurl",
    "colorspace", "cowplot", "gapminder", "sf", "ragg",
    "magick", "ggpattern", "quarto"
  )
)
```

Solutions to the problems in the exercise worksheets are provided, but you should not look at these solutions before the workshop and before you have made an honest attempt at completing an exercise on your own.

### 1. Color scales and color spaces

- Slides: [[html]](positconf2024-slides-colors.html)
- Exercises: [[html]](positconf2024-colors.html) [[qmd]](positconf2024-colors.qmd)


### 2. Plot design with themes and axes

- Worksheet: [[html]](positconf2024-themes.html) [[qmd]](positconf2024-themes.qmd)
- Solutions: [[html]](positconf2024-themes-solutions.html)

### 3. Sprucing up your legends

- Worksheet: [[html]](positconf2024-legends.html) [[qmd]](positconf2024-legends.qmd)
- Solutions: [[html]](positconf2024-legends-solutions.html) 

### 4. Gradient and pattern fills

- Worksheet: [[html]](positconf2024-pattern-fill.html) [[qmd]](positconf2024-pattern-fill.qmd)
- Solutions: [[html]](positconf2024-pattern-fill-solutions.html) 
